### ISSUE TITLE
Empty strings

### ISSUE THREAD

**Issue by daytonlowell** [TehShrike/joi-sql#10]
So Joi doesn't consider an empty string as valid. This is from their docs: 

> Note that the empty string is not allowed by default and must be enabled with allow(''). Don't over think, just remember that the empty string is not a valid string by default. Also, don't ask to change it or argue why it doesn't make sense. This topic is closed.

[Docs Link](https://hapi.dev/family/joi/api/?v=17.0.2#string)

If I made a PR that added `.allow('')` to strings, would you accept that?

**Comment by TehShrike** [comment]
Published as 1.4.0
